services:
  bnpl-api:
    build: .
    container_name: bnpl-risk-api
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:/app/mlruns
