name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'task-*'
  pull_request:
    branches:
      - main

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.14'

      - name: Upgrade pip, setuptools, wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel --upgrade-strategy eager

      - name: Preinstall critical dependencies
        run: |
          pip install numpy==2.3.5 scipy==1.16.3 scikit-learn==1.3.3

      - name: Install remaining dependencies
        run: pip install --no-deps -r requirements.txt

      - name: Run lint checks
        run: |
          pip install flake8
          flake8 src tests

      - name: Run unit & API tests
        run: |
          pip install pytest pytest-html
          pytest --maxfail=1 --disable-warnings -q --html=report.html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.html
